#!/bin/sh
# Copyright (C) 2026 David Nichols
# SPDX-License-Identifier: MIT
set -eu
unset QORE_MODULE_DIR QORE_MODULE_DIR_ONLY QORE_INCLUDE_DIR LD_LIBRARY_PATH LD_PRELOAD
unset FREETDS FREETDSCONF TDSVER TDSDUMP TDSDUMPCONFIG
cp test/freetds-offline.qtest "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
exec /usr/bin/qore freetds-offline.qtest -v
